### PR TITLE
notifications fixes

### LINKED ISSUE #308: add woker node to cdh can not work
{"level":"info","ts":1589017791.0068526,"logger":"controller_kubedirectorcluster","msg":"waiting for replicas count for role{worker}: 2 -> 4","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017791.0146863,"logger":"controller_kubedirectorcluster","msg":"waiting for replicas count for role{worker}: 2 -> 4","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017851.0559814,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017851.0559926,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017851.277333,"logger":"controller_kubedirectorcluster","msg":"creating file{/etc/guestconfig/configmeta.json} in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017851.6776502,"logger":"controller_kubedirectorcluster","msg":"creating file{/etc/guestconfig/configmeta.json} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017853.518963,"logger":"controller_kubedirectorcluster","msg":"creating file{/tmp/configcli.tgz} in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017853.9157438,"logger":"controller_kubedirectorcluster","msg":"creating file{/tmp/configcli.tgz} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017855.542778,"logger":"controller_kubedirectorcluster","msg":"running configcli setup in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017855.9417949,"logger":"controller_kubedirectorcluster","msg":"running configcli setup in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017857.6660178,"logger":"controller_kubedirectorcluster","msg":"running app config setup in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017858.0749185,"logger":"controller_kubedirectorcluster","msg":"running app config setup in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017859.6916547,"logger":"controller_kubedirectorcluster","msg":"running app config in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017860.0988066,"logger":"controller_kubedirectorcluster","msg":"running app config in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017861.7157881,"logger":"controller_kubedirectorcluster","msg":"initial config ongoing for member{kdss-k227s-3} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.126658,"logger":"controller_kubedirectorcluster","msg":"initial config ongoing for member{kdss-k227s-2} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.1326196,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-3}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.132619,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.241284,"logger":"controller_kubedirectorcluster","msg":"initial config done for member{kdss-k227s-3} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.33518,"logger":"controller_kubedirectorcluster","msg":"initial config ongoing for member{kdss-k227s-2} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.3405993,"logger":"controller_kubedirectorcluster","msg":"reading file{/opt/guestconfig/configure.status} in pod{kdss-k227s-2}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.4455178,"logger":"controller_kubedirectorcluster","msg":"initial config done for member{kdss-k227s-2} in role{worker}","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}
{"level":"info","ts":1589017862.4511223,"logger":"controller_kubedirectorcluster","msg":"stable","Request.Namespace":"cdh","Request.Name":"cdh5142cm-uat"}

I add 2 more worker nodes to the cdh cluster, but looks it  not  notify new members about member changes to master and old worker nodes in 0.4.1 which work well with 0.4.0

### PR DESCRIPTION
**Pull request by joel-bluedata**
* **Don't update LastSetupGeneration too early.** If there are any members currently in transitional state, they might be on the way to generate additional notifies related to this gen on future handler passes. So don't update LastSetupGeneration until all members have exited transitional state. Fixes #308 . Should be backported to 0.4.2.

* **Update spec gen for member add/remove.** It was incrementing only for connections changes and not for other changes. (Also, we don't need to do atomic int operations to increment it.)

* **Fix defaultEventList.** A typo in the JSON tag for defaultEventList meant that our internal DefaultEventList field was never populated, always nil.

* **Correctly honor eventList.** When queuing notifies, the code was checking the event list for the role of the added/deleted member, rather than the event list of the member that was receiving the notify.

Also a cosmetic fix for one of the app JSON files.

### CODE REVIEW

File: pkg/controller/kubedirectorcluster/cluster.go [hunk 1]
```diff
@@ -308,15 +310,9 @@ func (r *ReconcileKubeDirectorCluster) syncCluster(
...
-		if cr.Status.SpecGenerationToProcess == nil {
-			initSpecGen := int64(1)
-			cr.Status.SpecGenerationToProcess = &initSpecGen
-		}
-		if currentHash != cr.Status.LastConnectionHash {
-			incremented := atomic.AddInt64(cr.Status.SpecGenerationToProcess, 1)
-			cr.Status.SpecGenerationToProcess = &incremented
-			cr.Status.LastConnectionHash = currentHash
-		}
+		incremented := *cr.Status.SpecGenerationToProcess + int64(1)
```
Comment (kmathur2) [inline pkg/controller/kubedirectorcluster/cluster.go:313]: does it matter atomic increment v/s this? Just trying to understand the pros and cons.

**Comment by kmathur2** [comment]
Look good.

File: pkg/controller/kubedirectorcluster/cluster.go (hunk 1 above)
Comment (joel-bluedata) [reply pkg/controller/kubedirectorcluster/cluster.go:313]: No other goroutine is reading or writing this value so I don't think we need to incur the overhead of using atomic operations. Just generally speaking, we don't have parallel processes that are communicating through any shared-memory data structures.

Comment (kmathur2) [reply pkg/controller/kubedirectorcluster/cluster.go:313]: yes makes sense 👍
